### ISSUE TITLE
Isn't compatible with jQuery 3.0.0-alpha

### ISSUE THREAD

**Issue by sheriffderek** [viljamis/ResponsiveSlides.js#354]
Isn't compatible with jQuery 3.0.0-alpha

`Uncaught TypeError: $slide.size is not a function`

[Example on CodePen](http://codepen.io/sheriffderek/pen/mPVeXG)

**Comment by Requios** [comment]
I created a pull request to fix this over [here](https://github.com/viljamis/ResponsiveSlides.js/pull/360).
It's a simple fix: change 2 instances of size() into length, without brackets.

**Comment by GitFr33** [comment]
#360

**Comment by sheriffderek** [comment]
Merged on Aug 5 2016...
