### ISSUE TITLE
Position of slideshow not completely left

### ISSUE THREAD

**Issue by StijnMuller** [viljamis/ResponsiveSlides.js#376]
I'm new in creating websites and did manage to insert this slideshow feature. However, the slide show itself isn't positioned left, but seems a bit indented. I did some trouble shooting by creating a new page without a css but got the same result. I assume there is some indenting/positioning/padding in the script itself. Does anybody have a suggestion? Would be greatly appreciated!
Thanks,
Stijn.

**Comment by brinyside** [comment]
I am having the same problem. The image is not aligned completely left, but is indented about 18 px so the Prev arrow hangs out in space to the left of the image. CSS looks ok with left alignment and no padding. Were you able to fix this issue?  See it here: http://www.mettapartners.org/index-gallery.html

**Comment by StijnMuller** [comment]
Hi, I was able to override the coding in the css by using the index:

"<ul class="rslides" style="list-style: none; padding: 0; margin: 0; text-align: center;>"

Probably technically not the best way, but it did the trick for me.

**Comment by StijnMuller** [comment]
"<ul class="rslides" style="list-style: none; padding: 0; margin: 0; text-align: center;>"

**Comment by brinyside** [comment]
Thank you. I had earlier tried overriding with text-align, so was eager to try these additional styles, but no luck here. Opted to use a different slide show, rather than spend a ton of time troubleshooting. Appreciate the response.

**Comment by StijnMuller** [comment]
Great, going to close this issue. Might be handy to mention that other side though.
Best,
Stijn

**Comment by brinyside** [comment]
This slideshow worked well for me: https://github.com/leemark/better-simple-slideshow
