### ISSUE TITLE
HTTPS breaks it?

### ISSUE THREAD

**Issue by tjustinw3** [viljamis/ResponsiveSlides.js#401]
Great code... love it!
Works perfectly on the page with an HTTP:// call, but breaks under an HTTPS:// call.  Can't figure out why.
Example:
http://theceosystem.com/page-FreeTrial-1.php
https://theceosystem.com/page-FreeTrial-1.php

any thoughts?

Thx...
tjustinw3@hotmail.com

**Comment by arielsalminen** [comment]
@tjustinw3 Please check the browser console, you’re trying to load insecure content from http so the browser blocks it by default. See error:

![screenshot 2018-09-21 12 51 39](https://user-images.githubusercontent.com/671836/45874322-3adedf80-bd9d-11e8-8651-7d389fe6a447.png)

**Comment by tjustinw3** [comment]
perfect.  thx so much.
