### ISSUE TITLE
Uncaught TypeError: e.size is not a function

### ISSUE THREAD

**Issue by hzpcactus** [viljamis/ResponsiveSlides.js#406]
![image](https://user-images.githubusercontent.com/50914382/70861198-8ca4f400-1f65-11ea-8d70-2eb672a101c7.png)

**Comment by Larceniii** [comment]
I'm having the same issue... not sure where my problem is.

**Comment by hzpcactus** [comment]
> I'm having the same issue... not sure where my problem is.

Hello, it is due to the 'Jquery' version problem. The 'size()' method has been replaced with 'length' since Jquery 1.8.
Solution: replace 'size()' with 'length' in 'responsiveslides. Min. js'.
