### ISSUE TITLE
Stop after one or two cycles?

### ISSUE THREAD

**Issue by neoanchorite** [viljamis/ResponsiveSlides.js#46]
This is a great little script and has solved a problem (adding a slideshow to a fluid layout) that has been bugging me for a long time. If possible, could you tell me what needs changing in the script to make the cycle stop after the first or second run through (or n times). 

I've tried tweaking this line: 

```
     var idx = index + 1 < length ? index + 1 : 0;
```

and I can stop the slideshow going back to the first slide, but then it keeps fading the third slide in and out, which is not the desired outcome.

Any advice would be much appreciated. Thanks.

**Comment by mojodaddy** [comment]
Dear viljamis -- Working with v1.54 and can't seem to implement this fix from 2012. I'm just looking to stop the loop at th end of one cycle. Can you assist? 

The files I have in place are responsiveslides-call.js, responsiveslides.js and responsiveslides.min.js

Thanks for any help!

**Comment by Olfried2** [comment]
Hi Viljamis, same problem as mojodaddy but with v1.55. Just want to cycle 1or 2 time(s).
Couldn't you just add it to the actual code? 
Thanks in advance.

**Comment by sandusky** [comment]
I used the above snippet, then modified it slightly to have my slideshow end by cycling back to the first slides, so I have a full rotation plus 1. Thanks for the update!
