### ISSUE TITLE
Touch controls ?

### ISSUE THREAD

**Issue by samy** [viljamis/ResponsiveSlides.js#61]
Hi
Do you plan to use touch control support to ResponsiveSlide.js ? (like "taping on slider displays the next slide" or "swiping makes the slider to advance")

**Comment by tonymonckton** [comment]
Hi Dasmax,

        I've tried your code, but it doesn't seem to work.  any chance you could update the demo.html and send a zip file.
        desperately need this

tony

**Comment by dasmax** [comment]
Hi,
the above code worked fine for me. It's been a while so I can't help you any further on this. Sorry!

**Comment by AndersBillLinden** [comment]
Works for me, I removed the delay. Do not forget to add script tags for those jquery.event.move.js and jquery.event.swipe.js files!
